#+TITLE: auto-install-docdb
Automated installation DocDB on CentOS/SLOS.

* Introduction

DocDB is a powerful and flexible collaborative document server, which was developed for use by the BTeV collaboration at Fermilab and is now widely used in the scientific community. However its [[https://github.com/ericvaandering/DocDB][official installation instruction]] is too troublesome. To this end, [[https://github.com/brettviren][Mr. Brett Viren]] has proposed a [[https://github.com/brettviren/docdb-install]["docdb-install"]] package containing a Python script that can handle handles a bulk of the DocDB installation procedure. But there are three flies in the ointment: 1) his work is on Debian/Ubuntu, while  some people's server system is CentSO or Scientific Linux OS (SLOS), they can hardly use =agt-get= ; 2) there are some bugs remain in his codes; 3) He didn't develop the uninstaller. After I communicated with Mr. Brett Viren, he agreed to let me redevelop his code for free and open source on gitbhub, thanks for his generous.

* License

 * DocDB is available under the terms of the GNU Public License (GPL), version 2.

 * docdb-install is available under the terms of the GNU Public License (GPL), version 2.

 * auto-install-docdb is available under the terms of the GNU Public License (GPL), version 2.



