#+TITLE: auto-install-docdb
Automated installation DocDB on CentOS/SLOS.

* Introduction

DocDB is a powerful and flexible collaborative document server, which was developed for use by the BTeV collaboration at Fermilab and is now widely used in the scientific community. However its [[https://github.com/ericvaandering/DocDB][official installation instructions]] are too troublesome. To this end, [[https://github.com/brettviren][Mr. Brett Viren]] has proposed a [[https://github.com/brettviren/docdb-install]["docdb-install"]] package containing a Python script that can handle handles a bulk of the DocDB installation procedure. But there are three flies in the ointment: 1) his work is on Debian/Ubuntu, while  some people's server system is CentSO or Scientific Linux OS (SLOS), they can hardly use =agt-get= ; 2) there are some bugs remain in his codes; 3) He didn't develop the uninstaller. After I communicated with Mr. Brett Viren, he agreed to let me redevelop his codes for free and open source on github, thanks for his generous.

* License

 * [[https://github.com/ericvaandering/DocDB][DocDB]] is available under the terms of the GNU Public License (GPL), version 2.

 * [[https://github.com/brettviren/docdb-install][docdb-install]] is available under the terms of the GNU Public License (GPL), version 2.

 * [[https://github.com/ElonSteveWang/auto-install-docdb][auto-install-docdb]] is available under the terms of the GNU Public License (GPL), version 2.
 
* Environment
 * CentSO or Scientific Linux OS;
 * Python 2.x or more higher version (namely no special requirements, using your own version of the system);
 * Perl 5.x or more higher version (namely no special requirements, using your own version of the system);
 * Recommended Apache 2.x or more higher version.
 * Additional requirements refer to DocDB official notes.
 
* Installation instructions
Here is an actual installation:

#+BEGIN_EXAMPLE
  # cd /some/place
  # git clone https://github.com/ElonSteveWang/auto-install-docdb.git
  # cd auto-install-docdb
  # sudo DOCDB_PROJECT_NAME="HEP" DOCDB_WEB_HOST="120.0.0.0" DOCDB_PORT="8888" DOCDB_WEB_ROOT="HEP" DOCDB_DB_ROOT_PASS="db_root_pass"  python ./install_docdb.py
  # less /var/lib/docdb/installation.json
  Chrome/Firefox browser-> http://120.0.0.0:8888/cgi-bin/HEP/DocumentDatabase
#+END_EXAMPLE

* Common problems




 


