#+TITLE: auto-install-docdb
Automated installation DocDB on CentOS/SLOS.

* Introduction

DocDB is a powerful and flexible collaborative document server, which was developed for use by the BTeV collaboration at Fermilab and is now widely used in the scientific community. However its [[https://github.com/ericvaandering/DocDB][official installation instructions]] are too troublesome. To this end, [[https://github.com/brettviren][Mr. Brett Viren]] has proposed a [[https://github.com/brettviren/docdb-install]["docdb-install"]] package containing a Python script that can handle handles a bulk of the DocDB installation procedure. But there are three flies in the ointment: 1) his work is on Debian/Ubuntu, while  some people's server system is CentSO or Scientific Linux OS (SLOS), they can hardly use =agt-get= ; 2) there are some bugs remain in his codes; 3) He didn't develop the uninstaller. After I communicated with Mr. Brett Viren, he agreed to let me redevelop his codes for free and open source on github, thanks for his generous.

* License

 * [[https://github.com/ericvaandering/DocDB][DocDB]] is available under the terms of the GNU Public License (GPL), version 2.

 * [[https://github.com/brettviren/docdb-install][docdb-install]] is available under the terms of the GNU Public License (GPL), version 2.

 * [[https://github.com/ElonSteveWang/auto-install-docdb][auto-install-docdb]] is available under the terms of the GNU Public License (GPL), version 2.
 * Here is a ref superlink for [[http://www.gnu.org/licenses/old-licenses/gpl-2.0.html][GNU General Public License, version 2]].
 
* Environment
 * CentSO or Scientific Linux OS;
 * Python 2.x or more higher version (namely no special requirements, using your own version of the system);
 * Perl 5.x or more higher version (namely no special requirements, using your own version of the system);
 * Recommended Apache 2.x or more higher version.
 * Additional requirements refer to DocDB official notes.
 
* Installation instructions
Before you installation, please check the User and Group values in =httpd.conf=, default values both are =apache=. If not, your need to add =DOCDB_WEB_APACHE_USER=someone= and =DOCDB_WEB_APACHE_GROUP=somegroup= in the related bash commands of next instructions.

Here is an actual installation:

#+BEGIN_EXAMPLE
  # cd /some/place
  # git clone https://github.com/ElonSteveWang/auto-install-docdb.git
  # cd auto-install-docdb
  # sudo DOCDB_PROJECT_NAME="HEP" DOCDB_WEB_HOST="120.0.0.0" DOCDB_PORT="8888" DOCDB_WEB_ROOT="HEP" DOCDB_DB_ROOT_PASS="db_root_pass"  python ./install_docdb.py
  # less installation.json 
  Chrome/Firefox etc. browser -> http://120.0.0.0:8888/cgi-bin/HEP/DocumentDatabase
#+END_EXAMPLE

#+END_EXAMPLE
 * I strong recommend that you input DocDB web host, web port, web root and the password of user =root= the database.
 * As Mr. Brett Viren [[https://github.com/brettviren/docdb-install][pointed out]]: 
    *  Read the script for the full set of possible parameters; 
    * A file in JSON format will be produced to hold the parameters of the installation. Such a file can also be given to script to provide for the installation configuration. This file will contain passwords so protect it. Subsequent running will use the contents of this file to set the installation configuration parameters. 
    *  When no configuration file is explicitly given to the script and no configuration file is found in the canonical location then a set of default values coded in the script will be used. In addition, these default values can be overridden by a corresponding environment variable which is named by prepending =DOCDB_= to the upper-case version of the parameter name.
    *  There is no guarantee this package does not end up destroying all that you love and care about.
 * I used the DocDB installation package from a server in China by default in the =install_docdb.py= script for faster for faster clone. Overseas users can change the link to github by themselves, like https://github.com/brettviren/DocDB.git. As for the Official latest edition, you have to know its =CreateDatabase.SQL= is not supported by MySQL 5.x and more higher version and need to change "Username =text= NOT NULL default '' " to " Username =char(32)= NOT NULL default ''". The default DocDB installation package adds the bootstrap CSS files, which are not available in the official version.

* Common problems
  * Make sure your apache's httpd.conf and log paths are consistent with the script, otherwise enter the corresponding paths.
  * If the installation is successful, but the access failed, please check the error log and look for solutions via Google or Baidu. Here is an examples for solve a annoying question:
    * it reports =install_driver(mysql) failed: Can’t locate DBD/mysql.pm in @INC= ->  perl -MCPAN -e 'install DBD::mysql' . Please notice it contained single quotes instead of double quotes and "::" instead of "/"   (For Apache server).
    
  * useful commands:
    * yum install mysql-server
    * pip install mysqlclient
    * yum -y install perl-DBD-MySQL
    * yum -y install httpd-manual mod_ssl mod_perl mod_auth_mysql
    * yum -y install mysql-connector-odbc mysql-devel libdbi-dbd-mysql
    * perl -MCPAN -e 'install XML::Writer'
    * perl -MCPAN -e 'install CPAN'
    * perl -MCPAN -e 'install Benchmark'
    * yum install "perl(DBD::mysql)"   (double quotes for bash)
    * service mysqld restart / stop / start
    * service httpd restart / stop / start
    * systemctl restart httpd
    * perl DocumentDatabase   (check running statu in base)
    
    




 


